[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
token_faucet = "2m78e8ia8SuG9jxnLFtVBmvi5TsL8zaMWq3FRENAbRzZ"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
